"""
Pulsone Waveform Generation
============================
Implements point pulsone and spread pulsone waveforms for Zak-OTFS.

A pulsone is a pulse train modulated by a complex tone, used as the
fundamental waveform in Zak-OTFS systems.

Point Pulsone (Eq. 12 in [1]):
    b_{k0,l0}(t) = (1/sqrt(T_tau*T_nu)) * sum_k delta(t - k*T_tau - tau_0)
                    * exp(j*2*pi*(k*f0 + nu_0)*(t - tau_0))

    This waveform has perfect ambiguity properties (self-ambiguity supported
    only on the period lattice Lambda), but suffers from high PAPR (~15 dB).

Spread Pulsone (Eq. 18 in [1]):
    Generated by passing the point pulsone through a discrete chirp filter
    (phase rotation in the DD domain):
        h[m] = exp(j*pi*m^2 / M) for m = 0, ..., M-1

    This spreads energy across the Doppler axis, reducing PAPR to ~6 dB
    while maintaining good ambiguity properties on the rotated lattice Lambda*.

Reference:
    [1] Saif Khan Mohammed et al., "Zak-OTFS to Integrate Sensing the I/O
        Relation and Data Communication," arXiv:2404.04182, 2024.
"""

import numpy as np
from typing import Tuple, Optional


class PulsoneGenerator:
    """
    Generator for point and spread pulsone waveforms.

    Parameters
    ----------
    N : int
        Number of delay bins.
    M : int
        Number of Doppler bins.
    T_tau : float
        Delay period (seconds). Default 1.0.
    T_nu : float
        Doppler period (Hz). Default 1.0.
    """

    def __init__(self, N: int, M: int, T_tau: float = 1.0, T_nu: float = 1.0):
        self.N = N
        self.M = M
        self.T_tau = T_tau
        self.T_nu = T_nu
        self.delta_tau = T_tau / N   # Delay resolution
        self.delta_nu = T_nu / M    # Doppler resolution

    def point_pulsone(self, k0: int = 0, l0: int = 0) -> np.ndarray:
        """
        Generate a point pulsone in the DD domain.

        A point pulsone is a Kronecker delta in the DD domain:
            X[n, m] = delta[n - k0, m - l0]

        This corresponds to a single impulse at delay bin k0 and
        Doppler bin l0.

        Parameters
        ----------
        k0 : int
            Delay index (0 <= k0 < N). Default 0.
        l0 : int
            Doppler index (0 <= l0 < M). Default 0.

        Returns
        -------
        X_dd : np.ndarray, shape (N, M)
            Point pulsone in DD domain.
        """
        X_dd = np.zeros((self.N, self.M), dtype=complex)
        X_dd[k0 % self.N, l0 % self.M] = 1.0
        return X_dd

    def point_pulsone_time(self, k0: int = 0, l0: int = 0) -> np.ndarray:
        """
        Generate a point pulsone in the time domain.

        The time-domain representation of a point pulsone at (k0, l0)
        is obtained via OTFS modulation (ISFFT + Heisenberg).

        Parameters
        ----------
        k0 : int
            Delay index.
        l0 : int
            Doppler index.

        Returns
        -------
        s : np.ndarray, shape (N*M,)
            Time-domain point pulsone signal.
        """
        from otfs_modem import OTFSModem
        modem = OTFSModem(self.N, self.M)
        X_dd = self.point_pulsone(k0, l0)
        return modem.modulate(X_dd)

    def spread_pulsone(self, k0: int = 0, l0: int = 0) -> np.ndarray:
        """
        Generate a spread pulsone in the DD domain.

        A spread pulsone is generated by applying a discrete chirp filter
        to the point pulsone in the DD domain:

            X_spread[n, m] = X_point[n, m] * exp(j*pi*n^2 / N)

        The chirp filter spreads the impulse across the delay axis,
        distributing energy more uniformly and reducing PAPR.

        Parameters
        ----------
        k0 : int
            Delay index.
        l0 : int
            Doppler index.

        Returns
        -------
        X_dd : np.ndarray, shape (N, M)
            Spread pulsone in DD domain.
        """
        X_point = self.point_pulsone(k0, l0)

        # Discrete chirp filter along delay axis
        n = np.arange(self.N)
        chirp = np.exp(1j * np.pi * n**2 / self.N)

        # Apply chirp filter (element-wise multiplication along delay axis)
        X_spread = X_point * chirp[:, np.newaxis]

        return X_spread

    def spread_pulsone_time(self, k0: int = 0, l0: int = 0) -> np.ndarray:
        """
        Generate a spread pulsone in the time domain.

        Parameters
        ----------
        k0 : int
            Delay index.
        l0 : int
            Doppler index.

        Returns
        -------
        s : np.ndarray, shape (N*M,)
            Time-domain spread pulsone signal.
        """
        from otfs_modem import OTFSModem
        modem = OTFSModem(self.N, self.M)
        X_dd = self.spread_pulsone(k0, l0)
        return modem.modulate(X_dd)

    def chirp_filter(self) -> np.ndarray:
        """
        Return the discrete chirp filter coefficients.

        h[n] = exp(j*pi*n^2 / N), n = 0, ..., N-1

        Returns
        -------
        h : np.ndarray, shape (N,)
            Chirp filter coefficients.
        """
        n = np.arange(self.N)
        return np.exp(1j * np.pi * n**2 / self.N)

    def rotated_lattice_indices(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Compute the indices of the rotated lattice Lambda*.

        The rotated lattice is obtained by applying the chirp filter
        transformation to the original lattice. For a chirp with
        parameter alpha = 1/N, the rotated indices are:

            (n*, m*) = (n, m + alpha*n mod M)

        Returns
        -------
        n_rot : np.ndarray, shape (N*M,)
            Rotated delay indices.
        m_rot : np.ndarray, shape (N*M,)
            Rotated Doppler indices.
        """
        n_orig = np.arange(self.N)
        m_orig = np.arange(self.M)

        n_rot = []
        m_rot = []
        for n in n_orig:
            for m in m_orig:
                n_rot.append(n)
                m_rot.append((m + n) % self.M)

        return np.array(n_rot), np.array(m_rot)
