"""
OFDM Ambiguity Function Analysis for ISAC

This module implements ambiguity function analysis for OFDM-based waveforms,
comparing with LFM (chirp) radar signals. The ambiguity function characterizes
the resolution and sidelobe properties of radar waveforms.

Mathematical Background:
The ambiguity function χ(τ, ν) measures the response of a matched filter to a
signal with delay τ and Doppler shift ν:
    χ(τ, ν) = ∫ s(t) s*(t-τ) e^{j2πνt} dt

For OFDM signals with N subcarriers:
    s(t) = (1/√N) Σ[k=0 to N-1] X[k] e^{j2πkΔf t}

where X[k] are QAM-modulated symbols and Δf is the subcarrier spacing.
"""

import numpy as np
from scipy import signal
from typing import Tuple, Optional


def generate_ofdm_signal(
    n_subcarriers: int = 64,
    cp_len: int = 16,
    mod_order: int = 4,
    bandwidth: float = 20e6
) -> np.ndarray:
    """
    Generate OFDM time-domain signal.
    
    Parameters
    ----------
    n_subcarriers : int
        Number of subcarriers (N)
    cp_len : int
        Cyclic prefix length in samples
    mod_order : int
        Modulation order (2=BPSK, 4=QPSK, 16=16QAM, 64=64QAM)
    bandwidth : float
        Total bandwidth in Hz
        
    Returns
    -------
    np.ndarray
        Complex time-domain OFDM signal with CP
        
    Notes
    -----
    The OFDM signal is generated by:
    1. Generate random QAM symbols
    2. Apply IFFT to get time-domain OFDM symbol
    3. Prepend cyclic prefix
    
    s(t) = (1/√N) Σ X[k] * exp(j2πkΔf t)
    """
    # Generate random QAM symbols
    n_bits = int(np.log2(mod_order))
    n_total_bits = n_subcarriers * n_bits
    bits = np.random.randint(0, 2, n_total_bits)
    
    # QAM modulation using constellation mapping
    symbols = _qam_modulate(bits, mod_order)
    
    # Ensure we have exactly n_subcarriers symbols
    symbols = symbols[:n_subcarriers]
    
    # IFFT to get time-domain OFDM symbol
    time_signal = np.fft.ifft(symbols) * np.sqrt(n_subcarriers)
    
    # Prepend cyclic prefix (copy last cp_len samples to beginning)
    if cp_len > 0:
        cp = time_signal[-cp_len:]
        ofdm_signal = np.concatenate([cp, time_signal])
    else:
        ofdm_signal = time_signal.copy()
    
    return ofdm_signal


def _qam_modulate(bits: np.ndarray, mod_order: int) -> np.ndarray:
    """
    Modulate bits to QAM symbols.
    
    Parameters
    ----------
    bits : np.ndarray
        Binary data array
    mod_order : int
        Modulation order (2=BPSK, 4=QPSK, 16=16QAM, 64=64QAM)
        
    Returns
    -------
    np.ndarray
        Complex QAM symbols with unit average power
    """
    n_bits = int(np.log2(mod_order))
    n_symbols = len(bits) // n_bits
    
    if mod_order == 2:  # BPSK
        symbols = 2 * bits[:n_symbols] - 1
    elif mod_order == 4:  # QPSK
        I = 2 * bits[0::2][:n_symbols] - 1
        Q = 2 * bits[1::2][:n_symbols] - 1
        symbols = (I + 1j * Q) / np.sqrt(2)
    elif mod_order == 16:  # 16-QAM
        # Gray mapping for 16-QAM
        constellation = np.array([
            -3+3j, -3+1j, -3-3j, -3-1j,
            -1+3j, -1+1j, -1-3j, -1-1j,
             3+3j,  3+1j,  3-3j,  3-1j,
             1+3j,  1+1j,  1-3j,  1-1j
        ]) / np.sqrt(10)
        indices = bits.reshape(-1, 4).dot(1 << np.arange(4))
        indices = indices[:n_symbols]
        symbols = constellation[indices % 16]
    else:  # Default to QPSK
        I = 2 * bits[0::2][:n_symbols] - 1
        Q = 2 * bits[1::2][:n_symbols] - 1
        symbols = (I + 1j * Q) / np.sqrt(2)
    
    return symbols


def compute_ambiguity_function(
    signal_in: np.ndarray,
    tau_range: np.ndarray,
    nu_range: np.ndarray,
    fs: float = 1.0
) -> np.ndarray:
    """
    Compute 2D ambiguity function |χ(τ, ν)|².
    
    Parameters
    ----------
    signal_in : np.ndarray
        Complex input signal
    tau_range : np.ndarray
        Range of delay values (in samples)
    nu_range : np.ndarray
        Range of Doppler frequency values (normalized to fs)
    fs : float
        Sampling frequency (default 1.0 for normalized)
        
    Returns
    -------
    np.ndarray
        2D ambiguity function |χ(τ, ν)|² with shape (len(nu_range), len(tau_range))
        
    Notes
    -----
    χ(τ, ν) = ∫ s(t) s*(t-τ) e^{j2πνt} dt
    
    Computed using FFT-based approach for efficiency:
    1. Shift signal by each delay τ
    2. Correlate with original
    3. Apply frequency shift for each ν
    """
    n_tau = len(tau_range)
    n_nu = len(nu_range)
    n_signal = len(signal_in)
    
    # Normalize signal energy
    signal_norm = signal_in / np.sqrt(np.sum(np.abs(signal_in)**2))
    
    # Initialize ambiguity function
    af = np.zeros((n_nu, n_tau), dtype=complex)
    
    # Compute ambiguity function
    for i, nu in enumerate(nu_range):
        # Apply Doppler shift to original signal
        t = np.arange(n_signal)
        doppler_shifted = signal_norm * np.exp(1j * 2 * np.pi * nu * t / fs)
        
        for j, tau in enumerate(tau_range):
            tau_int = int(np.round(tau))
            
            # Create delayed version of signal
            if tau_int >= 0:
                # Positive delay: shift right, pad with zeros at start
                delayed = np.zeros_like(signal_norm)
                delayed[tau_int:] = signal_norm[:n_signal-tau_int] if tau_int < n_signal else 0
            else:
                # Negative delay: shift left, pad with zeros at end
                delayed = np.zeros_like(signal_norm)
                delayed[:n_signal+tau_int] = signal_norm[-tau_int:] if -tau_int < n_signal else 0
            
            # Correlation (matched filter response)
            af[i, j] = np.sum(doppler_shifted * np.conj(delayed))
    
    return np.abs(af)**2


def compute_ambiguity_function_ofdm(
    n_subcarriers: int = 64,
    cp_len: int = 16,
    tau_range: Optional[np.ndarray] = None,
    nu_range: Optional[np.ndarray] = None,
    n_tau_points: int = 101,
    n_nu_points: int = 101
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Optimized ambiguity function computation for OFDM signals.
    
    Parameters
    ----------
    n_subcarriers : int
        Number of subcarriers
    cp_len : int
        Cyclic prefix length
    tau_range : np.ndarray, optional
        Range of delay values (in samples)
    nu_range : np.ndarray, optional
        Range of Doppler frequency values
    n_tau_points : int
        Number of delay points if tau_range not provided
    n_nu_points : int
        Number of Doppler points if nu_range not provided
        
    Returns
    -------
    tuple
        (af_squared, tau_range, nu_range) where af_squared is |χ(τ, ν)|²
        
    Notes
    -----
    This optimized version leverages OFDM structure:
    - Uses subcarrier frequency responses directly
    - Exploits orthogonality for faster computation
    """
    # Generate OFDM signal
    ofdm_signal = generate_ofdm_signal(n_subcarriers, cp_len)
    
    signal_len = len(ofdm_signal)
    
    # Default ranges
    if tau_range is None:
        tau_range = np.linspace(-signal_len//2, signal_len//2, n_tau_points)
    if nu_range is None:
        nu_range = np.linspace(-1.0/n_subcarriers, 1.0/n_subcarriers, n_nu_points) * n_subcarriers
    
    # Use general computation (for correctness, can be optimized further)
    af = compute_ambiguity_function(ofdm_signal, tau_range, nu_range)
    
    return af, tau_range, nu_range


def generate_lfm_signal(
    bandwidth: float = 20e6,
    pulse_width: float = 10e-6,
    fs: float = 40e6
) -> np.ndarray:
    """
    Generate Linear Frequency Modulated (LFM/chirp) signal.
    
    Parameters
    ----------
    bandwidth : float
        Sweep bandwidth in Hz
    pulse_width : float
        Pulse duration in seconds
    fs : float
        Sampling frequency in Hz
        
    Returns
    -------
    np.ndarray
        Complex LFM signal
        
    Notes
    -----
    LFM signal: s(t) = exp(jπ * K * t²) where K = B/T is the chirp rate
    
    The LFM waveform has the "thumbtack" ambiguity function with
    excellent range-Doppler resolution properties.
    """
    n_samples = int(pulse_width * fs)
    t = np.arange(n_samples) / fs
    
    # Chirp rate
    K = bandwidth / pulse_width
    
    # LFM signal (centered at f=0)
    lfm_signal = np.exp(1j * np.pi * K * t**2)
    
    return lfm_signal


def plot_ambiguity_3d(
    af: np.ndarray,
    tau_range: np.ndarray,
    nu_range: np.ndarray,
    title: str = "Ambiguity Function",
    save_path: Optional[str] = None,
    db_scale: bool = True,
    db_limit: float = -40
) -> None:
    """
    Plot 3D surface of ambiguity function.
    
    Parameters
    ----------
    af : np.ndarray
        2D ambiguity function |χ(τ, ν)|²
    tau_range : np.ndarray
        Delay values
    nu_range : np.ndarray
        Doppler frequency values
    title : str
        Plot title
    save_path : str, optional
        Path to save figure
    db_scale : bool
        If True, plot in dB scale
    db_limit : float
        Lower limit for dB scale
        
    Notes
    -----
    The 3D surface plot reveals:
    - Peak at origin (zero delay, zero Doppler)
    - Sidelobe structure
    - Resolution properties
    """
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D
    
    TAU, NU = np.meshgrid(tau_range, nu_range)
    
    if db_scale:
        # Convert to dB
        af_plot = 10 * np.log10(af + 1e-15)
        af_plot = np.clip(af_plot, db_limit, 0)
        z_label = "|χ(τ, ν)|² (dB)"
    else:
        af_plot = af
        z_label = "|χ(τ, ν)|²"
    
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')
    
    surf = ax.plot_surface(TAU, NU, af_plot, cmap='jet', alpha=0.8)
    
    ax.set_xlabel('Delay τ (samples)')
    ax.set_ylabel('Doppler ν (normalized)')
    ax.set_zlabel(z_label)
    ax.set_title(title)
    
    fig.colorbar(surf, shrink=0.5, aspect=5)
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close()
    else:
        plt.show()


def plot_ambiguity_contour(
    af: np.ndarray,
    tau_range: np.ndarray,
    nu_range: np.ndarray,
    title: str = "Ambiguity Function Contour",
    save_path: Optional[str] = None,
    db_scale: bool = True,
    levels: Optional[list] = None
) -> None:
    """
    Plot contour of ambiguity function.
    
    Parameters
    ----------
    af : np.ndarray
        2D ambiguity function |χ(τ, ν)|²
    tau_range : np.ndarray
        Delay values
    nu_range : np.ndarray
        Doppler frequency values
    title : str
        Plot title
    save_path : str, optional
        Path to save figure
    db_scale : bool
        If True, plot in dB scale
    levels : list, optional
        Contour levels
        
    Notes
    -----
    Contour plots are essential for understanding:
    - 3dB resolution ellipse
    - Sidelobe ridge patterns
    - Doppler-delay coupling
    """
    import matplotlib.pyplot as plt
    
    TAU, NU = np.meshgrid(tau_range, nu_range)
    
    if db_scale:
        af_plot = 10 * np.log10(af + 1e-15)
        if levels is None:
            levels = [-3, -6, -10, -20, -30, -40]
        z_label = "|χ(τ, ν)|² (dB)"
    else:
        af_plot = af
        if levels is None:
            levels = np.linspace(0, np.max(af), 10)
        z_label = "|χ(τ, ν)|²"
    
    fig, ax = plt.subplots(figsize=(10, 8))
    
    contour = ax.contour(TAU, NU, af_plot, levels=levels, colors='black')
    contourf = ax.contourf(TAU, NU, af_plot, levels=50, cmap='jet')
    
    ax.clabel(contour, inline=True, fontsize=8)
    ax.set_xlabel('Delay τ (samples)')
    ax.set_ylabel('Doppler ν (normalized)')
    ax.set_title(title)
    
    fig.colorbar(contourf, label=z_label)
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close()
    else:
        plt.show()


def compute_range_resolution(bandwidth: float) -> float:
    """
    Compute theoretical range resolution.
    
    Parameters
    ----------
    bandwidth : float
        Signal bandwidth in Hz
        
    Returns
    -------
    float
        Range resolution in meters
        
    Notes
    -----
    Range resolution: ΔR = c / (2B)
    
    where c is speed of light (3×10⁸ m/s) and B is bandwidth.
    
    This is the fundamental limit - the 3dB width of the autocorrelation
    function determines the minimum separation of two targets.
    """
    c = 3e8  # Speed of light
    return c / (2 * bandwidth)


def compute_doppler_resolution(coherent_time: float) -> float:
    """
    Compute theoretical Doppler resolution.
    
    Parameters
    ----------
    coherent_time : float
        Coherent processing interval in seconds
        
    Returns
    -------
    float
        Doppler resolution in Hz
        
    Notes
    -----
    Doppler resolution: Δν = 1 / T
    
    where T is the coherent processing interval (observation time).
    
    This is determined by the inverse of the signal duration -
    longer observation enables finer Doppler discrimination.
    """
    return 1.0 / coherent_time


def compute_papr(signal_in: np.ndarray) -> float:
    """
    Compute Peak-to-Average Power Ratio (PAPR).
    
    Parameters
    ----------
    signal_in : np.ndarray
        Complex signal
        
    Returns
    -------
    float
        PAPR in linear scale
        
    Notes
    -----
    PAPR = max(|s(t)|²) / E[|s(t)|²]
    
    OFDM signals have high PAPR due to superposition of subcarriers.
    LFM signals have constant amplitude (PAPR = 1).
    """
    instantaneous_power = np.abs(signal_in)**2
    peak_power = np.max(instantaneous_power)
    avg_power = np.mean(instantaneous_power)
    
    return peak_power / avg_power


def compute_3db_resolution(tau_range: np.ndarray, af_cut: np.ndarray) -> float:
    """
    Compute 3dB resolution from ambiguity function cut.
    
    Parameters
    ----------
    tau_range : np.ndarray
        Delay values
    af_cut : np.ndarray
        1D cut of ambiguity function
        
    Returns
    -------
    float
        3dB resolution (width at half power)
    """
    af_normalized = af_cut / np.max(af_cut)
    half_power = 0.5  # -3dB = half power
    
    # Find crossings of half power level
    crossings = np.where(np.diff(np.sign(af_normalized - half_power)))[0]
    
    if len(crossings) >= 2:
        # Interpolate for better accuracy
        tau1 = tau_range[crossings[0]]
        tau2 = tau_range[crossings[-1]]
        return abs(tau2 - tau1)
    else:
        return np.nan


def theoretical_ofdm_ambiguity(
    n_subcarriers: int,
    tau: np.ndarray,
    nu: np.ndarray
) -> np.ndarray:
    """
    Compute theoretical OFDM ambiguity function.
    
    Parameters
    ----------
    n_subcarriers : int
        Number of subcarriers
    tau : np.ndarray
        Delay values (normalized by symbol duration)
    nu : np.ndarray
        Doppler values (normalized by subcarrier spacing)
        
    Returns
    -------
    np.ndarray
        Theoretical |χ(τ, ν)|²
        
    Notes
    -----
    For ideal OFDM with random QAM symbols:
    |χ(τ, ν)|² ≈ |sin(πNν) / sin(πν)|² * sinc²(τ) (simplified)
    
    The sidelobe envelope decays as 1/ν² for Doppler cuts,
    and as sinc² for delay cuts.
    """
    TAU, NU = np.meshgrid(tau, nu)
    
    # Doppler response (Dirichlet kernel squared)
    # Handle division by zero at nu = 0
    denom = np.sin(np.pi * NU)
    numer = np.sin(np.pi * n_subcarriers * NU)
    
    # Where denominator is near zero, use limit value
    doppler_response = np.zeros_like(NU)
    small_denom = np.abs(denom) < 1e-10
    doppler_response[small_denom] = n_subcarriers**2
    doppler_response[~small_denom] = (numer[~small_denom] / denom[~small_denom])**2
    
    # Delay response (sinc envelope)
    delay_response = np.sinc(TAU)**2
    
    # Combined ambiguity function (simplified)
    af = doppler_response * delay_response / n_subcarriers**2
    
    return af


if __name__ == "__main__":
    print("OFDM Ambiguity Function Module")
    print("=" * 40)
    
    # Quick test
    signal = generate_ofdm_signal(n_subcarriers=64, cp_len=16)
    print(f"Generated OFDM signal with {len(signal)} samples")
    
    lfm = generate_lfm_signal(bandwidth=20e6, pulse_width=10e-6)
    print(f"Generated LFM signal with {len(lfm)} samples")
    
    print(f"\nRange resolution (20 MHz): {compute_range_resolution(20e6)*1000:.2f} m")
    print(f"Doppler resolution (10 ms): {compute_doppler_resolution(10e-3):.2f} Hz")
    
    print(f"\nOFDM PAPR: {compute_papr(signal):.2f}")
    print(f"LFM PAPR: {compute_papr(lfm):.2f}")
