"""
OFDM Ambiguity Function Analysis for ISAC

This module implements ambiguity function analysis for OFDM-based waveforms,
comparing with LFM (chirp) radar signals. The ambiguity function characterizes
the resolution and sidelobe properties of radar waveforms.

Mathematical Background:
The ambiguity function χ(τ, ν) measures the response of a matched filter to a
signal with delay τ and Doppler shift ν. This implementation returns normalized
power ``|χ(τ,ν)|² / E²``:
    χ(τ, ν) = ∫ s(t) s*(t-τ) e^{j2πνt} dt

For OFDM signals with N subcarriers:
    s(t) = (1/√N) Σ[k=0 to N-1] X[k] e^{j2πkΔf t}

where X[k] are QAM-modulated symbols and Δf is the subcarrier spacing.
"""

import math
from typing import Optional, Tuple

import numpy as np


def _complex_component_scale(value: np.ndarray) -> float:
    """Return max(|Re|, |Im|) without overflowing complex magnitude."""
    return float(
        max(
            np.max(np.abs(value.real), initial=0.0),
            np.max(np.abs(value.imag), initial=0.0),
        )
    )


def _normalize_complex(value: np.ndarray, scale: float) -> np.ndarray:
    """Normalize finite complex components without complex-division overflow."""
    with np.errstate(divide="raise", invalid="raise", over="raise", under="ignore"):
        return value.real / scale + 1j * (value.imag / scale)


def _compensated_complex_sum(values: np.ndarray) -> complex:
    """Sum finite complex terms without discarding cancellation tails."""

    return complex(
        math.fsum(float(value) for value in values.real),
        math.fsum(float(value) for value in values.imag),
    )


def generate_ofdm_signal(
    n_subcarriers: int = 64,
    cp_len: int = 16,
    mod_order: int = 4,
    rng: Optional[np.random.Generator] = None,
) -> np.ndarray:
    """
    Generate OFDM time-domain signal.

    Parameters
    ----------
    n_subcarriers : int
        Number of subcarriers (N)
    cp_len : int
        Cyclic prefix length in samples
    mod_order : int
        Modulation order (2=BPSK, 4=QPSK, 16=16QAM, 64=64QAM)
    rng : Generator, optional
        Random generator. Pass a seeded generator for repeatable symbols.
    Returns
    -------
    np.ndarray
        Complex time-domain OFDM signal with CP

    Notes
    -----
    The OFDM signal is generated by:
    1. Generate random QAM symbols
    2. Apply IFFT to get time-domain OFDM symbol
    3. Prepend cyclic prefix

    s(t) = (1/√N) Σ X[k] * exp(j2πkΔf t)
    """
    if not isinstance(n_subcarriers, int) or n_subcarriers <= 0:
        raise ValueError("n_subcarriers must be a positive integer")
    if not isinstance(cp_len, int) or not 0 <= cp_len <= n_subcarriers:
        raise ValueError("cp_len must be an integer in [0, n_subcarriers]")

    # This function returns normalized discrete-time samples. Physical sample
    # rate/bandwidth belongs in the ambiguity-function axes, not in samples
    # that would otherwise be bit-identical while pretending to use bandwidth.
    n_bits = int(np.log2(mod_order))
    n_total_bits = n_subcarriers * n_bits
    rng = np.random.default_rng() if rng is None else rng
    if not isinstance(rng, np.random.Generator):
        raise TypeError("rng must be a numpy.random.Generator")
    bits = rng.integers(0, 2, n_total_bits)

    # QAM modulation using constellation mapping
    symbols = _qam_modulate(bits, mod_order)

    # Ensure we have exactly n_subcarriers symbols
    symbols = symbols[:n_subcarriers]

    # IFFT to get time-domain OFDM symbol
    time_signal = np.fft.ifft(symbols) * np.sqrt(n_subcarriers)

    # Prepend cyclic prefix (copy last cp_len samples to beginning)
    if cp_len > 0:
        cp = time_signal[-cp_len:]
        ofdm_signal = np.concatenate([cp, time_signal])
    else:
        ofdm_signal = time_signal.copy()

    return ofdm_signal


def _qam_modulate(bits: np.ndarray, mod_order: int) -> np.ndarray:
    """
    Modulate bits to QAM symbols.

    Parameters
    ----------
    bits : np.ndarray
        Binary data array
    mod_order : int
        Modulation order (2=BPSK, 4=QPSK, 16=16QAM, 64=64QAM)

    Returns
    -------
    np.ndarray
        Complex QAM symbols with unit average power
    """
    if not isinstance(mod_order, int) or mod_order < 2:
        raise ValueError("mod_order must be an integer >= 2")
    n_bits = int(np.log2(mod_order))
    if 2**n_bits != mod_order or (mod_order != 2 and n_bits % 2):
        raise ValueError("mod_order must be BPSK or a square power-of-two QAM order")
    bits = np.asarray(bits)
    if bits.ndim != 1 or np.any((bits != 0) & (bits != 1)):
        raise ValueError("bits must be a one-dimensional binary array")
    if len(bits) % n_bits:
        raise ValueError("bit count must be divisible by log2(mod_order)")
    n_symbols = len(bits) // n_bits

    if mod_order == 2:  # BPSK
        symbols = 2 * bits[:n_symbols] - 1
    else:
        axis_bits = n_bits // 2
        grouped = bits.reshape(n_symbols, n_bits)
        weights = 1 << np.arange(axis_bits - 1, -1, -1)
        i_index = grouped[:, :axis_bits] @ weights
        q_index = grouped[:, axis_bits:] @ weights
        side = int(np.sqrt(mod_order))
        i_level = 2 * i_index - (side - 1)
        q_level = 2 * q_index - (side - 1)
        normalization = np.sqrt(2.0 * (mod_order - 1) / 3.0)
        symbols = (i_level + 1j * q_level) / normalization

    return symbols


def compute_ambiguity_function(
    signal_in: np.ndarray,
    tau_range: np.ndarray,
    nu_range: np.ndarray,
    fs: float = 1.0
) -> np.ndarray:
    """
    Compute normalized 2D ambiguity power ``|χ(τ,ν)|² / E²``.

    Parameters
    ----------
    signal_in : np.ndarray
        Complex input signal
    tau_range : np.ndarray
        Integer delay values in samples. Fractional delays are rejected rather
        than silently rounded.
    nu_range : np.ndarray
        Doppler frequencies in Hz.
    fs : float
        Sampling frequency (default 1.0 for normalized)

    Returns
    -------
    np.ndarray
        Normalized ambiguity power with shape
        ``(len(nu_range), len(tau_range))``. The origin equals one.

    Notes
    -----
    χ(τ, ν) = ∫ s(t) s*(t-τ) e^{j2πνt} dt

    Computed using direct discrete summation:
    1. Shift signal by each delay τ
    2. Correlate with original
    3. Apply frequency shift for each ν
    """
    signal_in = np.asarray(signal_in, dtype=complex)
    tau_range = np.asarray(tau_range)
    nu_range = np.asarray(nu_range, dtype=float)
    if signal_in.ndim != 1 or signal_in.size == 0 or not np.all(np.isfinite(signal_in)):
        raise ValueError("signal_in must be a non-empty finite one-dimensional array")
    amplitude_scale = _complex_component_scale(signal_in)
    if amplitude_scale <= 0:
        raise ValueError("signal_in must have positive energy")
    if not np.isfinite(fs) or fs <= 0:
        raise ValueError("fs must be positive and finite")
    if not np.all(np.isfinite(tau_range)) or not np.all(np.isfinite(nu_range)):
        raise ValueError("tau_range and nu_range must be finite")
    if tau_range.ndim != 1 or nu_range.ndim != 1:
        raise ValueError("tau_range and nu_range must be one-dimensional")
    if not np.all(tau_range == np.rint(tau_range)):
        raise ValueError("tau_range must contain integer sample delays")
    integer_info = np.iinfo(np.intp)
    tau_integer_values = [int(value) for value in tau_range]
    if any(
        value < integer_info.min or value > integer_info.max
        for value in tau_integer_values
    ):
        raise ValueError("tau_range is outside the representable sample-delay domain")
    tau_samples = np.asarray(tau_integer_values, dtype=np.intp)
    if len(np.unique(tau_samples)) != len(tau_samples):
        raise ValueError("tau_range must not contain duplicate sample delays")
    n_tau = len(tau_range)
    n_nu = len(nu_range)
    n_signal = len(signal_in)
    sample_indices = np.arange(n_signal, dtype=float)

    # Scale before squaring. Direct |signal|^2 underflows near 1e-200 and
    # overflows near 1e200 even though normalized ambiguity power is invariant
    # to every finite nonzero common amplitude scale.
    scaled_signal = _normalize_complex(signal_in, amplitude_scale)
    scaled_energy = math.fsum(
        float(value) for value in np.abs(scaled_signal) ** 2
    )
    signal_norm = scaled_signal / np.sqrt(scaled_energy)

    # Initialize ambiguity function
    af = np.zeros((n_nu, n_tau), dtype=complex)

    # Compute ambiguity function
    for i, nu in enumerate(nu_range):
        # Apply Doppler shift to original signal
        # Discrete Doppler is periodic modulo fs.  Reducing first avoids
        # overflow in nu/fs and in nu * (sample_index/fs) for finite extremes.
        cycles_per_sample = np.remainder(nu, fs) / fs
        doppler_shifted = signal_norm * np.exp(
            1j * 2 * np.pi * cycles_per_sample * sample_indices
        )

        for j, tau_int in enumerate(tau_samples):

            # Create delayed version of signal
            if tau_int >= 0:
                # Positive delay: shift right, pad with zeros at start
                delayed = np.zeros_like(signal_norm)
                delayed[tau_int:] = signal_norm[:n_signal-tau_int] if tau_int < n_signal else 0
            else:
                # Negative delay: shift left, pad with zeros at end
                delayed = np.zeros_like(signal_norm)
                delayed[:n_signal+tau_int] = signal_norm[-tau_int:] if -tau_int < n_signal else 0

            # Correlation (matched filter response)
            af[i, j] = _compensated_complex_sum(
                doppler_shifted * np.conj(delayed)
            )

    return np.abs(af)**2


def compute_ambiguity_function_ofdm(
    n_subcarriers: int = 64,
    cp_len: int = 16,
    tau_range: Optional[np.ndarray] = None,
    nu_range: Optional[np.ndarray] = None,
    n_tau_points: int = 101,
    n_nu_points: int = 101,
    rng: Optional[np.random.Generator] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Convenience ambiguity-function computation for one OFDM symbol.

    Parameters
    ----------
    n_subcarriers : int
        Number of subcarriers
    cp_len : int
        Cyclic prefix length
    tau_range : np.ndarray, optional
        Range of delay values (in samples)
    nu_range : np.ndarray, optional
        Range of Doppler frequency values
    n_tau_points : int
        Number of delay points if tau_range not provided
    n_nu_points : int
        Number of Doppler points if nu_range not provided
    rng : Generator, optional
        Random generator for the OFDM symbols.

    Returns
    -------
    tuple
        (af_squared, tau_range, nu_range) where af_squared is |χ(τ, ν)|²

    Notes
    -----
    This wrapper generates an OFDM symbol and calls the general discrete-time
    implementation. It is intentionally a correctness-oriented nested-loop
    reference, not an optimized transform implementation.
    """
    # Generate OFDM signal
    ofdm_signal = generate_ofdm_signal(n_subcarriers, cp_len, rng=rng)

    # Default ranges
    if tau_range is None:
        if not isinstance(n_tau_points, int) or n_tau_points < 1:
            raise ValueError("n_tau_points must be a positive integer")
        tau_range = np.arange(n_tau_points) - n_tau_points // 2
    if nu_range is None:
        if not isinstance(n_nu_points, int) or n_nu_points < 1:
            raise ValueError("n_nu_points must be a positive integer")
        # Normalized discrete-time sampling uses fs=1 Hz. This centered grid
        # stays within one Nyquist interval, includes zero, and avoids the
        # duplicated -fs/2 and +fs/2 endpoints.
        nu_range = (np.arange(n_nu_points) - n_nu_points // 2) / n_nu_points

    # Use the direct general computation.
    af = compute_ambiguity_function(ofdm_signal, tau_range, nu_range)

    return af, tau_range, nu_range


def generate_lfm_signal(
    bandwidth: float = 20e6,
    pulse_width: float = 10e-6,
    fs: float = 40e6,
    max_samples: int = 1_000_000,
) -> np.ndarray:
    """
    Generate Linear Frequency Modulated (LFM/chirp) signal.

    Parameters
    ----------
    bandwidth : float
        Sweep bandwidth in Hz
    pulse_width : float
        Pulse duration in seconds
    fs : float
        Sampling frequency in Hz
    max_samples : int
        Allocation guard for this direct reference implementation.

    Returns
    -------
    np.ndarray
        Complex LFM signal

    Notes
    -----
    LFM signal: s(t) = exp(jπ * K * t²) where K = B/T is the chirp rate

    A finite-duration LFM pulse has a slanted ambiguity ridge: delay and
    Doppler are coupled along a line whose slope is set by the chirp rate.
    It therefore should not be described as an ideal "thumbtack" waveform.
    """
    if not all(np.isfinite(value) and value > 0 for value in (bandwidth, pulse_width, fs)):
        raise ValueError("bandwidth, pulse_width, and fs must be positive and finite")
    if bandwidth > fs:
        raise ValueError("bandwidth must not exceed fs for the sampled baseband chirp")
    if not isinstance(max_samples, (int, np.integer)) or max_samples < 1:
        raise ValueError("max_samples must be a positive integer")
    with np.errstate(over="ignore", invalid="ignore"):
        sample_product = float(np.multiply(pulse_width, fs))
    if not np.isfinite(sample_product):
        raise ValueError("pulse_width * fs is outside the finite binary64 domain")
    if sample_product > max_samples:
        raise ValueError(
            f"requested LFM length exceeds max_samples={max_samples}"
        )
    n_samples = int(sample_product)
    if n_samples < 1:
        raise ValueError("pulse_width * fs must produce at least one sample")
    t = (np.arange(n_samples) - (n_samples - 1) / 2.0) / fs

    # Chirp rate
    with np.errstate(over="ignore", divide="ignore", invalid="ignore"):
        K = float(np.divide(bandwidth, pulse_width))
    if not np.isfinite(K):
        raise ValueError("chirp rate is outside the finite binary64 domain")

    # LFM signal centered at f=0, with approximate sweep -B/2 to +B/2.
    lfm_signal = np.exp(1j * np.pi * K * t**2)

    return lfm_signal


def plot_ambiguity_3d(
    af: np.ndarray,
    tau_range: np.ndarray,
    nu_range: np.ndarray,
    title: str = "Ambiguity Function",
    save_path: Optional[str] = None,
    db_scale: bool = True,
    db_limit: float = -40
) -> None:
    """
    Plot 3D surface of ambiguity function.

    Parameters
    ----------
    af : np.ndarray
        2D ambiguity function |χ(τ, ν)|²
    tau_range : np.ndarray
        Delay values
    nu_range : np.ndarray
        Doppler frequency values
    title : str
        Plot title
    save_path : str, optional
        Path to save figure
    db_scale : bool
        If True, plot in dB scale
    db_limit : float
        Lower limit for dB scale

    Notes
    -----
    The 3D surface plot reveals:
    - Peak at origin (zero delay, zero Doppler)
    - Sidelobe structure
    - Resolution properties
    """
    import matplotlib.pyplot as plt
    TAU, NU = np.meshgrid(tau_range, nu_range)

    if db_scale:
        # Convert to dB
        af_plot = 10 * np.log10(af + 1e-15)
        af_plot = np.clip(af_plot, db_limit, 0)
        z_label = "|χ(τ, ν)|² (dB)"
    else:
        af_plot = af
        z_label = "|χ(τ, ν)|²"

    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    surf = ax.plot_surface(TAU, NU, af_plot, cmap='jet', alpha=0.8)

    ax.set_xlabel('Delay τ (samples)')
    ax.set_ylabel('Doppler ν (Hz)')
    ax.set_zlabel(z_label)
    ax.set_title(title)

    fig.colorbar(surf, shrink=0.5, aspect=5)

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close()
    else:
        plt.show()


def plot_ambiguity_contour(
    af: np.ndarray,
    tau_range: np.ndarray,
    nu_range: np.ndarray,
    title: str = "Ambiguity Function Contour",
    save_path: Optional[str] = None,
    db_scale: bool = True,
    levels: Optional[list] = None
) -> None:
    """
    Plot contour of ambiguity function.

    Parameters
    ----------
    af : np.ndarray
        2D ambiguity function |χ(τ, ν)|²
    tau_range : np.ndarray
        Delay values
    nu_range : np.ndarray
        Doppler frequency values
    title : str
        Plot title
    save_path : str, optional
        Path to save figure
    db_scale : bool
        If True, plot in dB scale
    levels : list, optional
        Contour levels

    Notes
    -----
    Contour plots are essential for understanding:
    - 3dB resolution ellipse
    - Sidelobe ridge patterns
    - Doppler-delay coupling
    """
    import matplotlib.pyplot as plt

    TAU, NU = np.meshgrid(tau_range, nu_range)

    if db_scale:
        af_plot = 10 * np.log10(af + 1e-15)
        if levels is None:
            levels = [-40, -30, -20, -10, -6, -3]
        z_label = "|χ(τ, ν)|² (dB)"
    else:
        af_plot = af
        if levels is None:
            levels = np.linspace(0, np.max(af), 10)
        z_label = "|χ(τ, ν)|²"

    fig, ax = plt.subplots(figsize=(10, 8))

    contour = ax.contour(TAU, NU, af_plot, levels=levels, colors='black')
    contourf = ax.contourf(TAU, NU, af_plot, levels=50, cmap='jet')

    ax.clabel(contour, inline=True, fontsize=8)
    ax.set_xlabel('Delay τ (samples)')
    ax.set_ylabel('Doppler ν (Hz)')
    ax.set_title(title)

    fig.colorbar(contourf, label=z_label)

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close()
    else:
        plt.show()


def compute_range_resolution(bandwidth: float) -> float | np.ndarray:
    """
    Compute the conventional reciprocal-bandwidth range cell.

    Parameters
    ----------
    bandwidth : float
        Signal bandwidth in Hz

    Returns
    -------
    float
        Range resolution in meters

    Notes
    -----
    Range resolution: ΔR = c / (2B)

    where c is speed of light (3×10⁸ m/s) and B is bandwidth.

    ``c/(2B)`` is a common Rayleigh-style resolution convention. It is not the
    3 dB width: for a rectangular spectrum, the full half-power delay width is
    approximately ``0.886/B`` before conversion to two-way range.
    """
    values = np.asarray(bandwidth, dtype=float)
    if not np.all(np.isfinite(values)) or np.any(values <= 0):
        raise ValueError("bandwidth must be positive and finite")
    c = 3e8  # Speed of light
    with np.errstate(over="ignore", divide="ignore", invalid="ignore"):
        result = (c / 2.0) / values
    if not np.all(np.isfinite(result)):
        raise ValueError("range resolution is outside the finite binary64 domain")
    return float(result) if result.ndim == 0 else result


def compute_doppler_resolution(coherent_time: float) -> float | np.ndarray:
    """
    Compute theoretical Doppler resolution.

    Parameters
    ----------
    coherent_time : float
        Coherent processing interval in seconds

    Returns
    -------
    float
        Doppler resolution in Hz

    Notes
    -----
    Doppler resolution: Δν = 1 / T

    where T is the coherent processing interval (observation time).

    This is determined by the inverse of the signal duration -
    longer observation enables finer Doppler discrimination.
    """
    values = np.asarray(coherent_time, dtype=float)
    if not np.all(np.isfinite(values)) or np.any(values <= 0):
        raise ValueError("coherent_time must be positive and finite")
    with np.errstate(over="ignore", divide="ignore", invalid="ignore"):
        result = 1.0 / values
    if not np.all(np.isfinite(result)):
        raise ValueError("Doppler resolution is outside the finite binary64 domain")
    return float(result) if result.ndim == 0 else result


def compute_papr(signal_in: np.ndarray) -> float:
    """
    Compute Peak-to-Average Power Ratio (PAPR).

    Parameters
    ----------
    signal_in : np.ndarray
        Complex signal

    Returns
    -------
    float
        PAPR in linear scale

    Notes
    -----
    PAPR = max(|s(t)|²) / E[|s(t)|²]

    OFDM signals have high PAPR due to superposition of subcarriers.
    LFM signals have constant amplitude (PAPR = 1).
    """
    signal_in = np.asarray(signal_in)
    if signal_in.ndim != 1 or signal_in.size == 0 or not np.all(np.isfinite(signal_in)):
        raise ValueError("signal_in must be a non-empty finite one-dimensional array")
    amplitude_scale = _complex_component_scale(signal_in)
    if amplitude_scale <= 0:
        raise ValueError("PAPR is undefined for a zero-energy signal")
    # PAPR is scale invariant, so normalize before squaring to avoid binary64
    # underflow/overflow for otherwise valid finite inputs.
    instantaneous_power = np.abs(
        _normalize_complex(signal_in, amplitude_scale)
    ) ** 2
    peak_power = np.max(instantaneous_power)
    avg_power = np.mean(instantaneous_power)

    return float(peak_power / avg_power)


def compute_3db_resolution(tau_range: np.ndarray, af_cut: np.ndarray) -> float:
    """
    Compute 3dB resolution from ambiguity function cut.

    Parameters
    ----------
    tau_range : np.ndarray
        Delay values
    af_cut : np.ndarray
        1D cut of ambiguity function

    Returns
    -------
    float
        3dB resolution (width at half power)
    """
    tau_range = np.asarray(tau_range, dtype=float)
    af_cut = np.asarray(af_cut, dtype=float)
    if tau_range.ndim != 1 or af_cut.ndim != 1 or tau_range.shape != af_cut.shape:
        raise ValueError("tau_range and af_cut must be one-dimensional and equal length")
    if len(tau_range) < 3 or not np.all(np.isfinite(tau_range)) or not np.all(np.isfinite(af_cut)):
        raise ValueError("3 dB width requires at least three finite samples")
    if np.any(np.diff(tau_range) <= 0):
        raise ValueError("tau_range must be strictly increasing")
    peak = float(np.max(af_cut))
    if peak <= 0:
        raise ValueError("af_cut must have a positive peak")

    af_normalized = af_cut / peak
    half_power = 0.5  # -3dB = half power
    peak_index = int(np.argmax(af_normalized))

    left_below = peak_index - 1
    while left_below >= 0 and af_normalized[left_below] >= half_power:
        left_below -= 1
    right_below = peak_index + 1
    while right_below < len(af_normalized) and af_normalized[right_below] >= half_power:
        right_below += 1
    if left_below < 0 or right_below >= len(af_normalized):
        return np.nan

    left_crossing = np.interp(
        half_power,
        [af_normalized[left_below], af_normalized[left_below + 1]],
        [tau_range[left_below], tau_range[left_below + 1]],
    )
    right_crossing = np.interp(
        half_power,
        [af_normalized[right_below], af_normalized[right_below - 1]],
        [tau_range[right_below], tau_range[right_below - 1]],
    )
    return float(right_crossing - left_crossing)


if __name__ == "__main__":
    print("OFDM Ambiguity Function Module")
    print("=" * 40)

    # Quick test
    signal = generate_ofdm_signal(n_subcarriers=64, cp_len=16)
    print(f"Generated OFDM signal with {len(signal)} samples")

    lfm = generate_lfm_signal(bandwidth=20e6, pulse_width=10e-6)
    print(f"Generated LFM signal with {len(lfm)} samples")

    print(f"\nRange resolution (20 MHz): {compute_range_resolution(20e6)*1000:.2f} m")
    print(f"Doppler resolution (10 ms): {compute_doppler_resolution(10e-3):.2f} Hz")

    print(f"\nOFDM PAPR: {compute_papr(signal):.2f}")
    print(f"LFM PAPR: {compute_papr(lfm):.2f}")
